title: "Ruben Miranda - Data blog"
email: ruben.miranda.f@gmail.com
timezone: America/Santiago
baseurl: ""
permalink: "/:slug/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: RMiranda
paginate: 10
#disqus: 'disqus_5QSs1Dy586'
locale: es_CL
lang: es_CL
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
#ganalytics: UA-113961478-1

# Authors
authors:
  rmirfa:
    name: Rubén
    display_name: Rubén Miranda
    avatar: 'assets/images/my_avatar.jpg'
    email: ruben.miranda.f@gmail.com
    web: https://sarudalf3.github.io/
    twitter: https://twitter.com/sarudalf
    description: "Data curious!"
    github: https://github.com/sarudalf3

# Social
social:
  #instagram: https://www.instagram.com/bootstrapstarter/
  #facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
  twitter: https://twitter.com/sarudalf
  tumblr: https://sarudalf3.tumblr.com/
  linkedin: https://www.linkedin.com/in/rmirandaf
  github: https://github.com/sarudalf3

# Configuración global de slugs
slugify:
  mode: latin # Esto elimina tildes y caracteres especiales
  cased: false # ESTA ES LA CLAVE: 'false' fuerza todo a minúsculas

### Collections ###
collections:
  posts:
    permalink: /post/:slug/
  projects:
    output: true
    permalink: /:slug/

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "projects"
    values:
      layout: external

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives